-- Run this in Supabase SQL Editor for visitor analytics + final messages.
-- Safe to run after the older schema: the new columns are added only if missing.
-- No camera/microphone/video/audio tables are included.

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  visitor_id text,
  visit_number integer,
  recipient_id text not null,
  recipient_name text,
  nickname text,
  event_type text not null,
  detail jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  visitor_id text,
  visit_number integer,
  recipient_id text not null,
  recipient_name text,
  nickname text,
  message text not null,
  created_at timestamptz not null default now()
);

-- Add the return-visit columns to an already-created project.
alter table public.visitor_events add column if not exists visitor_id text;
alter table public.visitor_events add column if not exists visit_number integer;
alter table public.visitor_messages add column if not exists visitor_id text;
alter table public.visitor_messages add column if not exists visit_number integer;

alter table public.visitor_events enable row level security;
alter table public.visitor_messages enable row level security;

-- Anonymous visitors may INSERT only. They cannot SELECT other visitors' data.
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='visitor_events' and policyname='anon can insert visitor events') then
    create policy "anon can insert visitor events"
    on public.visitor_events for insert
    to anon with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='visitor_messages' and policyname='anon can insert visitor messages') then
    create policy "anon can insert visitor messages"
    on public.visitor_messages for insert
    to anon with check (true);
  end if;
end $$;

create index if not exists visitor_events_visitor_visit_idx
on public.visitor_events (visitor_id, visit_number, created_at);

create index if not exists visitor_messages_visitor_visit_idx
on public.visitor_messages (visitor_id, visit_number, created_at);

-- IMPORTANT: Do NOT create a public SELECT policy.
-- Read visitor data from the Supabase dashboard, or use a protected admin page/server function.


-- Recipient names are editable from the protected creator dashboard.
create table if not exists public.surprise_recipients (
  recipient_id text primary key,
  name text not null,
  updated_at timestamptz not null default now()
);

alter table public.surprise_recipients enable row level security;

-- The public site needs only the recipient name for the ?to=... link.
drop policy if exists "public can read surprise recipient names" on public.surprise_recipients;
create policy "public can read surprise recipient names"
on public.surprise_recipients
for select
to anon, authenticated
using (true);

create index if not exists surprise_recipients_updated_idx
on public.surprise_recipients (updated_at);

-- Seed/update these from config.js once. The creator dashboard can edit them later.
insert into public.surprise_recipients (recipient_id, name)
values
  ('sahela', 'Sahela'),
  ('sana', 'Sana'),
  ('saniya', 'Saniya'),
  ('pakeezah', 'Pakeezah'),
  ('gunchasanam', 'Guncha Sanam'),
  ('kashish', 'Kashish'),
  ('nazrana', 'Nazrana'),
  ('foryou', 'For You'),
  ('sidra', 'Sidra'),
  ('sanam', 'Sanam'),
  ('shafaque', 'Al Shafaque Fatmi'),
  ('friend', 'Friend')
on conflict (recipient_id) do nothing;
